name: Build PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup LaTeX environment
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
      
      - name: Build PDF documents
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            make build
      - name: Move PDFs to output
        run: |
          mkdir output
          mv *.pdf output/
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: output/
      - name: Upload main book
        uses: actions/upload-artifact@v4
        with:
          name: Book
          path: output/main.pdf