name: Build PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make image cache directory
        run: mkdir -p ~/image-cache
    
      - id: image-cache
        uses: actions/cache@v4
        with:
          path: ~/image-cache
          key: image-cache-${{ runner.os }}

      - name: Load cache if available
        if: steps.image-cache.outputs.cache-hit == 'true'
        run: docker load -i ~/image-cache/image.tar

      - name: Setup LaTeX environment
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
      - name: Save docker image to cache if not available
        if: steps.image-cache.outputs.cache-hit != 'true'
        run: docker save -o ~/image-cache/image.tar ghcr.io/xu-cheng/texlive-full:latest
      
      - name: Build PDF documents
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            make build
      - name: Move PDFs to output
        run: |
          mkdir output
          mv *.pdf output/
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: output/
      - name: Upload main book
        uses: actions/upload-artifact@v4
        with:
          name: Book
          path: output/main.pdf