name: Build PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX environment
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
            tlmgr install latexmk
            make build
      - name: Move PDFs to output
        run: |
          mkdir output
          mv *.pdf output/
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PDF Artifacts
          path: output/