name: Build PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup LaTeX environment
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
      
      - name: Build PDF documents
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            make build
      - name: Move PDFs to output
        run: |
          mkdir output
          cp *.pdf output/
      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PDFs
          path: output/
      - name: Upload main book
        uses: actions/upload-artifact@v4
        with:
          name: Book
          path: output/main.pdf
      - name: Build GitHub Pages
        run: make build-gh-page
      - name: Upload GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: pages.tar.gz
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4